services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inkarya-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_DSN=${DB_DSN}
    restart: unless-stopped
    networks:
      - inkarya-network

  db:
    image: postgres:15
    container_name: inkarya-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inkarya
    restart: unless-stopped
    networks:
      - inkarya-network

networks:
  inkarya-network:
    driver: bridge

volumes:
  pgdata:
